set -g default-shell /opt/homebrew/bin/nu
set-option -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
set -as terminal-features ",tmux-256color:RGB"
set -s escape-time 0
set -g mouse on

bind -n C-n last-pane
bind -n C-s send-keys C-l \; clear-history
bind -n C-j select-window -t 1
bind -n C-k select-window -t 2
bind -n C-l select-window -t 3

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

unbind %
bind | split-window -h

unbind \"
bind _ split-window -v

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z


bind r source-file ~/.tmux.conf
set -g base-index 1

bind -r a last-window

setw -g mode-keys vi
set -g set-clipboard on
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

# forget the find window.  That is for chumps
bind-key -n C-f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"

bind-key -r i run-shell "tmux neww tmux-cht.sh"

set -g pane-active-border-style "fg=cyan"
set -g status-style 'bg=#333333 fg=#aaaaaa'
set-option -g status-position bottom
set -g status-style 'bg=default fg=default'
set-option -g message-style "fg=default,bg=default"
setw -g window-status-current-format ' #I#[fg=colour255]:#[fg=colour255]#W#[fg=colour203]#F '
setw -g window-status-format ' #I#[fg=colour255]:#[fg=colour250]#W#[fg=colour244]#F '
