[directory]
style = "white"
truncation_length = 0
truncate_to_repo = false

[git_branch]
disabled = true

[git_commit]
disabled = true


[custom.jj]
when = "jj-starship detect"
shell = ["jj-starship", "--no-color"]
format = "[$output ]($style)"
style = "bold purple"
